### ISSUE TITLE
Hyperparameter differentiated configuration approach

### ISSUE THREAD

**Issue by lvyanru8200** [DataTunerX/meta-server#21]
How to differential configuration of hyperparameter cr used by finetunejob in one finetuneexperiment without a new hyperparameter cr.

**Comment by lvyanru8200** [comment]
Hyperparameter CRD positioning is a parameter group template , the template can be directly referenced , you can also modify the template based on .

Usage: A set of default value templates is built-in when the system is released. Users can create their own templates. Modification and deletion need to ensure that the template is not currently referenced by any task.

Differentiation: the task defines the name of the referenced template, and the overrides field describes which fields have been modified on top of the template, the overrides field can be empty. E.g.:
```yaml
ApiVersion: finetune.datatunerx.io/v1beta1
Kind: FinetuneJob
Metadata:
  Name: Pipeline Name  
Spec.
  Finetune:
    FineTuneSpec:
      LLM: Large Model Used CR  
      Dataset: Dataset used CR  
      Hyperparameter:
        HyperparameterRef: Hyperparameter used CR
        Overrides:
        - LearningRate: 0.6
```
Important Notes:
1. the parameter group template in the previous target cannot be deleted and modified when there is any reference to it.
2. add field in task's details-basic information to show overrides, styled as expandable tabs on mouse hover.
